### ISSUE TITLE
couldnot find model.py in fairseq-image-captioning

### ISSUE THREAD

**Issue by GISScience** [hiteshK03/Remote-sensing-image-captioning-with-transformer-and-multilabel-classification#3]
couldnot find model.py in fairseq-image-captioning.??

what is differenc ebetween fairseq and  fairseq-image-captioning??

looking forwrd to learn

**Comment by hiteshK03** [comment]
I have added all the remaining files.  
fairseq is pytorch library and fairseq-image-captioning has been created for  captioning.

**Comment by GISScience** [comment]
Thanks for quick reply. 

Its a great piece of work. 

Request you to please share trained model to quick check the working demo.

looking forward to connect with you.  

Thanks and regards,
cs20mds14013@iith.ac.in
7015182469
